services:
  server:
    build:
      context: ./server/
      dockerfile: Dockerfile
    environment:
      - PGHOST=db
      - PGDATABASE=${PGDB}
      - PGUSER=${PGUSER}
      - PGPASSWORD=${PGPASSWORD}
      - PGPORT=5432
    networks:
      - app-network
    ports:
      - "5001:5001"
    working_dir: "/home/node/app"
    depends_on:
      - db
  db:
    build:
      context: ./
      dockerfile: Dockerfile
    environment:
      - POSTGRES_USER=${PGUSER}
      - POSTGRES_HOST=${PGHOST}
      - POSTGRES_PASSWORD=${PGPASSWORD}
      - POSTGRES_DB=${PGDB}
    ports:
      - "${PGPORT:-5432}:5432"
    #   volumes:
    #     - ./sql:/docker-entrypoint-initdb.d
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
